allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  contextify: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoreScripts: true
onlyBuiltDependencies:
  - contextify
  - msw
  - sharp
  - unrs-resolver
